config/routes.rb
Rails.application.routes.draw do
  root "goals#index"

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :create, :show]
  resources :goals

  resources :comments, only: [:create, :destroy]
end

app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id               :integer          not null, primary key
#  body             :text             not null
#  commenter_id     :integer          not null
#  commentable_id   :integer          not null
#  commentable_type :string           not null
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#

class Comment < ActiveRecord::Base

  belongs_to :commentable, polymorphic: true
  belongs_to :commenter, class_name: :User

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id           :integer          not null, primary key
#  title        :string           not null
#  user_id      :integer          not null
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  is_completed :boolean          default("f")
#  description  :text
#  is_private   :boolean
#

class Goal < ActiveRecord::Base
  validates :title, :user_id, presence: true

  belongs_to :user

  has_many :comments, as: :commentable
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  session_token   :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base

  validates :username, :session_token, :password_digest, presence: true
  validates :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  has_many :goals
  has_many :comments, as: :commentable

  after_initialize :ensure_session_token

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil unless user && user.is_password?(password)
    user
  end

  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_session_token
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_session_token
    self.session_token = User.generate_session_token
    self.save!
    self.session_token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :logged_in?, :current_user

  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def logout
    current_user.reset_session_token
    session[:session_token] = nil
  end

  def ensure_logged_in
    redirect_to new_session_url unless logged_in?
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    comment = Comment.new(comment_params)
    comment.commenter_id = current_user.id
    unless comment.save
      flash[:errors] = comment.errors.full_messages
    end
    redirect_to (comment_params[:commentable_type] == "Goal" ? goal_url(comment.commentable_id) : user_url(comment.commentable_id))
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to (comment.commentable_type == "Goal" ? goal_url(comment.commentable_id) : user_url(comment.commentable_id))
  end

  private
  def comment_params
    params.require(:comment).permit(:body, :commentable_id, :commentable_type)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController
  before_action :ensure_logged_in, except: [:index, :show]
  before_action :ensure_owner, only: [:edit, :update, :destroy]

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def index
    @goals = Goal.where(is_private: false)
  end

  def show
    @goal = Goal.includes(comments: :commenter).includes(:user).find(params[:id])
    if @goal.is_private && current_user.id != @goal.user_id
      flash[:errors] = ["This goal is private"]
      redirect_to goals_url
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal.update_attributes(goal_params)
      redirect_to goal_url(@goal)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :edit
    end
  end

  def destroy
    goal = Goal.find(params[:id])
    goal.destroy
    redirect_to goals_url
  end

  def goal_params
    params.require(:goal).permit(:title, :description, :is_private, :is_completed)
  end

  def ensure_owner
    @goal = Goal.find(params[:id])
    redirect_to goals_url unless current_user.id == @goal.user_id
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    @user = User.find_by_credentials(params[:user][:username], params[:user][:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to goals_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    if current_user.id == params[:id]
      @user = User.includes(comments: :commenter).includes(:goals).find(params[:id])
    else
      @user = User
                .includes(comments: :commenter)
                .includes(:goals)
                .where("goals.is_private = ?", false)
                .references(:goals)
                .find(params[:id])
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def form_auth_token
    "<input type=\"hidden\" name=\"authenticity_token\" value=\"#{form_authenticity_token}\">".html_safe
  end
  
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% action = (@goal.persisted? ? goal_url(@goal) : goals_url) %>
<% method = (@goal.persisted? ? :patch : :post) %>
<% button_text = (@goal.persisted? ? "Update Goal" : "Create Goal") %>

<form action="<%= action %>" method="post">
  <%= form_auth_token %>
  <input type="hidden" name="_method" value="<%= method %>">

  <label for="title">Title<br>
    <input type="text" name="goal[title]" value="<%= @goal.title %>">
  </label><br>

  <label for="comment">Comment (optional)<br>
    <textarea name="goal[description]" rows="8" cols="80"><%= @goal.description %></textarea>
  </label><br>

  <input type="radio" name="goal[is_private]" value="false" <%= "checked" unless @goal.is_private %>>Public
  <input type="radio" name="goal[is_private]" value="true" <%= "checked" if @goal.is_private %>>Private<br>

  <% if @goal.persisted? %>
  <label for="completed">Completed
    <input type="checkbox" name="goal[is_completed]" <%= "checked" if @goal.is_completed %>>
  </label><br>
  <% end %>

  <input type="submit" value="<%= button_text %>">
</form>

app/views/goals/edit.html.erb
<h2>Update Goal</h2>

<%= render "form" %>

app/views/goals/index.html.erb
<h2>All Goals</h2>

<ul>
  <% @goals.each do |goal| %>
  <li><%= link_to goal.title, goal_url(goal) %></li>
  <% end %>
</ul>

app/views/goals/new.html.erb
<h2>Create Goal</h2>

<%= render "form" %>

app/views/goals/show.html.erb
<h2><%= @goal.title %></h2>
<h4><%= @goal.user.username %>'s Goal</h4>
<% if @goal.description %>
<p><%= @goal.description %></p>
<% end %>

<p><%= @goal.is_private ? "Private" : "Public" %></p>
<p><%= @goal.is_completed ? "Completed" : "Unaccomplished" %></p>

<% if current_user.id = @goal.user_id %>
<%= button_to "Edit Goal", edit_goal_url(@goal), method: :get %>
<% end %>


<h4>Comments</h4>
<ul>
  <% @goal.comments.each do |gc| %>
  <li>
    <%= gc.body %> (<%= gc.commenter.username %>)
    <%= button_to "Remove Comment", comment_url(gc), method: :delete %>
  </li>
  <% end %>
</ul>

<% if logged_in? %>
<h4>Add a comment</h4>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="comment[commentable_id]" value="<%= @goal.id %>">
  <input type="hidden" name="comment[commentable_type]" value="Goal">
  <%= form_auth_token %>

  <label for="comment">Comment
    <textarea name="comment[body]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Add Comment">
</form>
<% end %>


<%= link_to "All Goals", goals_url %>

app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error| %>
  <li><%= error %></li>
  <% end %>
</ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render "layouts/errors" %>

  <% if logged_in? %>
  <%= button_to current_user.username, user_url(current_user), method: :get %>
  <%= button_to "Sign Out", session_url, method: :delete %>
  <% else %>
  <% unless current_page?(controller: :users, action: :new) %>
  <%= button_to "Sign Up", new_user_url, method: :get %>
  <% end %>
  <% unless current_page?(controller: :sessions, action: :new) %>
  <%= button_to "Sign In", new_session_url, method: :get %>
  <% end %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Sign Up</h2>

<form action="<%= users_url %>" method="post">
  <%= form_auth_token %>

  <label for="username">Username
    <input type="text" name="user[username]">
  </label>

  <label for="password">Password
    <input type="password" name="user[password]">
  </label>

  <input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
<h2><%= @user.username %></h2>

<h4>Goals</h4>
<ul>
  <% if @user.goals.length == 0 %>
  <li>(no goals)</li>
  <% else %>
  <% @user.goals.each do |goal| %>
  <li><%= link_to goal.title, goal_url(goal) %></li>
  <% end %>
  <% end %>
</ul>

<h4>Comments</h4>
<ul>
  <% @user.comments.each do |uc| %>
  <li>
    <%= uc.body %> (<%= uc.commenter.username %>)
    <%= button_to "Remove Comment", comment_url(uc), method: :delete %>
  </li>
  <% end %>
</ul>

<% if logged_in? %>
<h4>Add a comment</h4>
<form action="<%= comments_url %>" method="post">
  <input type="hidden" name="comment[commentable_id]" value="<%= @user.id %>">
  <input type="hidden" name="comment[commentable_type]" value="User">
  <%= form_auth_token %>

  <label for="comment">Comment
    <textarea name="comment[body]" rows="8" cols="80"></textarea>
  </label>

  <input type="submit" value="Add Comment">
</form>
<% end %>

<%= link_to "Add a Goal", new_goal_url %>
<%= link_to "All Goals", goals_url %>